### ISSUE TITLE
Some errors with the latest build

### ISSUE THREAD

**Issue by donmega** [losbagos/totalmailboxdeath#9]
@losbagos 

Love the script, great job! The new version has some issues for me:

**- Like the old version, it can't find the kitty.ico file. Maybe you can upload it? For now i always remove that row.**

C:\Temp\mailboxdef2\totalmailboxdeath-main>python main.py

DevTools listening on ws://127.0.0.1:58016/devtools/browser/edf79682-8340-44d1-b801-458f1d22a07d
Traceback (most recent call last):
  File "C:\Temp\mailboxdef2\totalmailboxdeath-main\main.py", line 47, in <module>
    tmdApp.iconbitmap("kitty.ico")
  File "C:\Users\Wu\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 2080, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "kitty.ico" not defined

**- Can't run the new version because tmdShank is not defined in main.py:**

C:\Temp\mailboxdef2\totalmailboxdeath-main>python main.py

DevTools listening on ws://127.0.0.1:58083/devtools/browser/15589697-dd4d-4d8f-811c-c43d90c4137d
Traceback (most recent call last):
  File "C:\Temp\mailboxdef2\totalmailboxdeath-main\main.py", line 156, in <module>
    tmdContactSubmit_button = tkinter.Button (tmdApp, text='run contact form spammer', background=Pink, command = tmdShank)
NameError: name 'tmdShank' is not defined

Keep up the great job!!

**Comment by losbagos** [comment]
seems like a silly error on my part, ill look at this now

**Comment by losbagos** [comment]
these should be fixed now! just some silly little errors i shouldve picked up on! let me know if theres any more issues!

**Comment by donmega** [comment]
Yes, working great now, Thanks chief!
